default: DeathStarHeist.java Choice.java Endings.java DeathStarInterior.java BaseMap.java DogFight.java
	javac DeathStarHeist.java Choice.java Endings.java DeathStarInterior.java BaseMap.java DogFight.java

run: DeathStarHeist.class Choice.class Endings.class DeathStarInterior.class BaseMap.class DogFight.class
	java DeathStarHeist Choice Endings DeathStarInterior BaseMap DogFight
clean:
	rm -f *.class